# Generated by Django 6.0.4 on 2026-05-04 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Codigo')),
                ('direccion', models.TextField(verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('region', models.CharField(max_length=100, verbose_name='Region')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Bodega',
                'verbose_name_plural': 'Bodegas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, verbose_name='Numero de Lote')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('cantidad', models.PositiveIntegerField(default=0, verbose_name='Cantidad Disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=10, verbose_name='Stock Minimo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrado')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('bodega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_stock', to='inventario.bodega', verbose_name='Bodega')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_stock', to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Item de Stock',
                'verbose_name_plural': 'Items de Stock',
                'ordering': ['fecha_vencimiento'],
                'unique_together': {('producto', 'bodega', 'numero_lote')},
            },
        ),
    ]
