# Generated by Django 6.0.4 on 2026-05-04 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(choices=[('webpay_credito', 'WebPay Credito'), ('webpay_debito', 'WebPay Debito'), ('transferencia', 'Transferencia Bancaria')], max_length=20, verbose_name='Metodo de Pago')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('fallido', 'Fallido'), ('reembolsado', 'Reembolsado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('id_transaccion', models.CharField(blank=True, max_length=100, verbose_name='ID de Transaccion')),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=50, verbose_name='Codigo de Autorizacion')),
                ('ultimos_cuatro', models.CharField(blank=True, max_length=4, verbose_name='Ultimos 4 digitos')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('completado_en', models.DateTimeField(blank=True, null=True, verbose_name='Completado el')),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_confirmados', to=settings.AUTH_USER_MODEL, verbose_name='Confirmado por')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_boleta', models.CharField(max_length=50, unique=True, verbose_name='Nro de Boleta')),
                ('rut_emisor', models.CharField(default='76.000.000-0', max_length=12, verbose_name='RUT Emisor')),
                ('rut_receptor', models.CharField(blank=True, max_length=12, verbose_name='RUT Receptor')),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Neto')),
                ('monto_iva', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='IVA (19%)')),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='boletas/', verbose_name='PDF Boleta')),
                ('emitida_en', models.DateTimeField(auto_now_add=True, verbose_name='Emitida el')),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='boleta', to='pagos.pago', verbose_name='Pago')),
            ],
            options={
                'verbose_name': 'Boleta Electronica',
                'verbose_name_plural': 'Boletas Electronicas',
                'ordering': ['-emitida_en'],
            },
        ),
    ]
