# Generated by Django 6.0.2 on 2026-05-17 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='auditado_en',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Auditoria'),
        ),
        migrations.AddField(
            model_name='pago',
            name='auditado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_auditados', to=settings.AUTH_USER_MODEL, verbose_name='Auditado por'),
        ),
        migrations.AddField(
            model_name='pago',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes/', verbose_name='Comprobante de Transferencia'),
        ),
        migrations.AddField(
            model_name='pago',
            name='cumple_politicas',
            field=models.BooleanField(default=False, verbose_name='Cumple Politicas'),
        ),
        migrations.AddField(
            model_name='pago',
            name='notas_tributarias',
            field=models.TextField(blank=True, verbose_name='Notas Tributarias'),
        ),
    ]
