# Generated by Django 6.0.4 on 2026-05-15 01:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlianzaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clinica', models.CharField(max_length=200, verbose_name='Nombre de la Clínica')),
                ('rut_clinica', models.CharField(blank=True, max_length=12, verbose_name='RUT Clínica')),
                ('contacto_nombre', models.CharField(max_length=200, verbose_name='Nombre del Contacto')),
                ('contacto_email', models.EmailField(max_length=254, verbose_name='Email del Contacto')),
                ('contacto_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Región')),
                ('tipo_alianza', models.CharField(choices=[('distribucion_exclusiva', 'Distribución Exclusiva'), ('contrato_suministro', 'Contrato de Suministro'), ('precio_preferencial', 'Precio Preferencial'), ('consignacion', 'Consignación')], default='contrato_suministro', max_length=30, verbose_name='Tipo de Alianza')),
                ('estado', models.CharField(choices=[('prospecto', 'Prospecto'), ('en_negociacion', 'En Negociación'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='prospecto', max_length=20, verbose_name='Estado')),
                ('descuento_acordado', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento Acordado (%)')),
                ('volumen_mensual_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Volumen Mensual Estimado (CLP)')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha de Fin')),
                ('notas', models.TextField(blank=True, verbose_name='Notas Internas')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alianzas_creadas', to=settings.AUTH_USER_MODEL, verbose_name='Creada por')),
            ],
            options={
                'verbose_name': 'Alianza Estratégica',
                'verbose_name_plural': 'Alianzas Estratégicas',
                'ordering': ['-creada_en'],
            },
        ),
    ]
