# Generated by Django 6.0.4 on 2026-05-15 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('pedidos', '0002_pedido_descuento_pedido_vendedor_alter_pedido_estado'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Nº Cotización')),
                ('nombre_cliente', models.CharField(max_length=200, verbose_name='Nombre del Cliente')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='Email del Cliente')),
                ('telefono_cliente', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion_cliente', models.TextField(blank=True, verbose_name='Dirección')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('convertida', 'Convertida a Pedido')], default='borrador', max_length=15, verbose_name='Estado')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Descuento')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('valida_hasta', models.DateField(verbose_name='Válida Hasta')),
                ('notas', models.TextField(blank=True, verbose_name='Notas / Condiciones')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Cliente / Institución')),
                ('pedido_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_origen', to='pedidos.pedido', verbose_name='Pedido Generado')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemCotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.cotizacion', verbose_name='Cotización')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Ítem de Cotización',
                'verbose_name_plural': 'Ítems de Cotización',
            },
        ),
        migrations.CreateModel(
            name='VisitaAsesoramiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=200, verbose_name='Institución')),
                ('contacto_nombre', models.CharField(max_length=200, verbose_name='Persona de Contacto')),
                ('contacto_cargo', models.CharField(blank=True, max_length=100, verbose_name='Cargo')),
                ('tipo', models.CharField(choices=[('visita_tecnica', 'Visita Técnica'), ('capacitacion', 'Capacitación'), ('demostracion', 'Demostración de Producto'), ('seguimiento', 'Seguimiento Comercial'), ('reclamo', 'Atención de Reclamo')], default='visita_tecnica', max_length=20, verbose_name='Tipo de Visita')),
                ('fecha_visita', models.DateField(verbose_name='Fecha de Visita')),
                ('resultado', models.CharField(choices=[('exitosa', 'Exitosa'), ('pendiente', 'Pendiente de Seguimiento'), ('sin_interes', 'Sin Interés'), ('reprogramada', 'Reprogramada')], default='exitosa', max_length=20, verbose_name='Resultado')),
                ('productos_presentados', models.TextField(blank=True, verbose_name='Productos Presentados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('proxima_accion', models.TextField(blank=True, verbose_name='Próxima Acción')),
                ('fecha_seguimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Seguimiento')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Registrada el')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitas', to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Visita de Asesoramiento',
                'verbose_name_plural': 'Visitas de Asesoramiento',
                'ordering': ['-fecha_visita'],
            },
        ),
    ]
