# Generated by Django 6.0.4 on 2026-05-04 22:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transportista', models.CharField(choices=[('chilexpress', 'Chilexpress'), ('starken', 'Starken'), ('bluexpress', 'Blue Express'), ('correos', 'Correos de Chile')], default='chilexpress', max_length=50, verbose_name='Transportista')),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, verbose_name='Nro de Seguimiento')),
                ('estado', models.CharField(choices=[('etiqueta_creada', 'Etiqueta Creada'), ('recogido', 'Recogido'), ('en_transito', 'En Transito'), ('en_reparto', 'En Reparto'), ('entregado', 'Entregado'), ('devuelto', 'Devuelto')], default='etiqueta_creada', max_length=20, verbose_name='Estado')),
                ('entrega_estimada', models.DateField(blank=True, null=True, verbose_name='Entrega Estimada')),
                ('peso_kg', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Peso (kg)')),
                ('despachado_en', models.DateTimeField(blank=True, null=True, verbose_name='Despachado el')),
                ('entregado_en', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('pedido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='envio', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Envio',
                'verbose_name_plural': 'Envios',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='EventoSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=100, verbose_name='Estado')),
                ('ubicacion', models.CharField(blank=True, max_length=200, verbose_name='Ubicacion')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripcion')),
                ('fecha_hora', models.DateTimeField(verbose_name='Fecha/Hora')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='envios.envio', verbose_name='Envio')),
            ],
            options={
                'verbose_name': 'Evento de Seguimiento',
                'verbose_name_plural': 'Eventos de Seguimiento',
                'ordering': ['-fecha_hora'],
            },
        ),
    ]
