# Generated by Django 6.0.4 on 2026-05-04 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('productos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=20, unique=True, verbose_name='Nro de Pedido')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado por Ejecutivo'), ('preparando', 'En Preparacion'), ('despachado', 'Despachado'), ('entregado', 'Entregado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('urgente', 'Urgente'), ('critico', 'Critico - Urgencia Medica')], default='normal', max_length=20, verbose_name='Prioridad')),
                ('tipo_despacho', models.CharField(choices=[('express', 'Despacho Express'), ('normal', 'Despacho Normal')], default='normal', max_length=20, verbose_name='Tipo de Despacho')),
                ('direccion_envio', models.TextField(verbose_name='Direccion de Envio')),
                ('ciudad_envio', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('region_envio', models.CharField(max_length=100, verbose_name='Region')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Subtotal')),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de Envio')),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='IVA')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total')),
                ('numero_seguimiento', models.CharField(blank=True, max_length=100, verbose_name='Nro de Seguimiento')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creacion')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizacion')),
                ('aprobado_en', models.DateTimeField(blank=True, null=True, verbose_name='Aprobado el')),
                ('despachado_en', models.DateTimeField(blank=True, null=True, verbose_name='Despachado el')),
                ('entregado_en', models.DateTimeField(blank=True, null=True, verbose_name='Entregado el')),
                ('bodega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.bodega', verbose_name='Bodega de Origen')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('numero_lote', models.CharField(blank=True, max_length=50, verbose_name='Nro de Lote')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.producto', verbose_name='Producto')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pedidos.pedido', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item del Pedido',
                'verbose_name_plural': 'Items del Pedido',
            },
        ),
    ]
