# Generated by Django 6.0.4 on 2026-05-04 22:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('ejecutivo', 'Ejecutivo de Cuentas'), ('logistica', 'Operador Logistico'), ('analista', 'Analista de Finanzas'), ('institucion', 'Institucion / Clinica'), ('paciente', 'Paciente')], default='paciente', max_length=20, verbose_name='Rol')),
                ('rut', models.CharField(blank=True, max_length=12, verbose_name='RUT')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Telefono')),
                ('direccion', models.TextField(blank=True, verbose_name='Direccion')),
                ('ciudad', models.CharField(blank=True, max_length=100, verbose_name='Ciudad')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razon Social')),
                ('rut_empresa', models.CharField(blank=True, max_length=12, verbose_name='RUT Empresa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
    ]
