# Generated by Django 6.0.4 on 2026-05-11 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='codigo_vendedor',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Codigo de Vendedor'),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('ejecutivo', 'Ejecutivo de Cuentas'), ('logistica', 'Operador Logistico'), ('analista', 'Analista de Finanzas'), ('vendedor', 'Vendedor de Insumos'), ('institucion', 'Institucion / Clinica'), ('paciente', 'Paciente')], default='paciente', max_length=20, verbose_name='Rol'),
        ),
    ]
