# Generated by Django 6.0.2 on 2026-05-17 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_perfilusuario_codigo_vendedor_and_more'),
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='bodega',
            field=models.ForeignKey(blank=True, help_text='Solo para operadores logísticos: la bodega que gestionan.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='inventario.bodega', verbose_name='Bodega Asignada'),
        ),
    ]
